global:
  scrape_interval:     5s
  evaluation_interval: 5s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'dbcheck'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
