version: '3'

services:

  apiapp_c:
    build:
      context:    ${build_context}
      dockerfile: ${build_dockerfile}
    ports:
      - 40102:5000
    environment:
      - access_token=${access_token}
